### PR TITLE
Fix bug (remove little padding at the top of sticky header)

### PR DESCRIPTION
**Pull request by Eimji**
Hello,

This is a small fix to remove the top padding above the sticky header.

Thanks.

### CODE REVIEW

**Comment by michael-mueller** [comment]
i would love to see that PR merged

**Comment by slightfoot** [comment]
Thanks @Eimji

**Comment by slightfoot** [comment]
Decided to revert this change and apply the fix a different way.

**Comment by slightfoot** [comment]
Fixed as-of v0.3.0.

**Pull request merged**
