### PR TITLE
Fix the problem that Flutter upgrades to 3.0.0

### PR DESCRIPTION
**Pull request by jack24254029**

### CODE REVIEW

**Comment by jack24254029** [comment]
@brianegan @slightfoot @mhadaily @nodinosaur 
Help this PR to merge into master and publish a new version for Flutter 3.0.0, please.
Thank you very much.

**Comment by mhadaily** [comment]
Thanks for the PR, I believe if we merge this we have to release a major version.

**Comment by slightfoot** [comment]
Thanks for the PR @jack24254029. I've decided to make some other changes. But will upgrade the package to Flutter v3 and release a new version now.

**Comment by RoyalCoder88** [comment]
when the update will be available?

**Comment by slightfoot** [comment]
Sorry for the delay. Fixing as few others things so I'll push 0.3.0 in a few minutes.

**Comment by slightfoot** [comment]
Update published.

**Pull request closed without merging**
